Refactor Source/Branch/Commit Artifact Collection

diff --git a/.gitlab-ci.yml b/.gitlab-ci.yml
--- a/.gitlab-ci.yml
+++ b/.gitlab-ci.yml
@@ -1,8 +1,8 @@
 stages:
-  - cncf-artifacts
-  - cross-cloud
-  - cross-project
-  - cncf-e2e
+  - Build
+  - Artifacts
+  - Cross-Cloud
+  - End-To-End
 
 before_script:
   - export BASE_URL=${BASE_URL:-$(echo $CI_PROJECT_URL |  cut -d'/' -f1-3)}
@@ -10,110 +10,152 @@ before_script:
   - mkdir -p ./data ; touch ./data/empty.env
   - for envfile in data/*env ; do source $envfile ; echo ----- $envfile ---- ; cat $envfile ; done
 
-# Fetch Artifacts based on Branch Passed by Trigger
-kubernetes-build-branch:
-  image: buildpack-deps:stretch
-  stage: cncf-artifacts
-  script:
-    - apt update && apt -y install jq
-    - echo "$KUBERNETES_BRANCH"
-    - >
-      if [ -z "${KUBERNETES_BRANCH}" ]; then
-        exit 0 #Should Show Skipped on Gitlab CI FIXME
-      else
-        echo "Checking for Latest Build"
-        curl -s -L -o data/kubernetes.url "${BASE_URL}/kubernetes/kubernetes/builds/artifacts/${KUBERNETES_BRANCH}/file/release.env?job=container"
-        if cat data/kubernetes.url | sed -n 's/.*href="\([^"]*\).*/\1/p' | grep artifacts/raw ; then
-        KUBERNETES_RELEASE_ENV=$(cat data/kubernetes.url | sed -n 's/.*href="\([^"]*\).*/\1/p' | grep artifacts/raw | tail -1)
-        curl -o data/kubernetes.env -L ${BASE_URL}/$KUBERNETES_RELEASE_ENV
-        cat data/kubernetes.env
-        else
-          PROJECT_PIPELINE=$(curl -X POST -F token=$KUBERNETES_CI_JOB_TOKEN -F ref=${KUBERNETES_BRANCH} -F "variables[BUILD_TRIGGER]=yes" https://gitlab.cncf.ci/api/v4/projects/14/trigger/pipeline | jq '.id')
-          echo 'Wait for Build "FIX ME / HACK"'
-          until [ "$JOB_STATUS" == '"success"' ]; do JOB_STATUS="$(curl -s --header "PRIVATE-TOKEN:${TOKEN}" "https://gitlab.cncf.ci/api/v4/projects/14/pipelines/${PROJECT_PIPELINE}/jobs?scope=success" | jq '.[] | select(.name=="container") | .status')" ; sleep 0.5 ; done ; echo 'Build Compleate'
-          PROJECT_JOB=$(curl --header "PRIVATE-TOKEN:${TOKEN}" "https://gitlab.cncf.ci/api/v4/projects/14/pipelines/${PROJECT_PIPELINE}/jobs?scope=success" | jq '.[] | select(.name=="container") | .id') 
-          curl -s -o data/kubernetes.env -L "$BASE_URL/kubernetes/kubernetes/-/jobs/${PROJECT_JOB}/artifacts/raw/release.env"
-          cat data/kubernetes.env
-        fi
-      fi
-  artifacts:
-    name: "${CI_JOB_NAME}_${CI_COMMIT_REF_NAME}"
-    untracked: true
-    expire_in: 5 weeks
-    paths:
-      - ./data
-
-# Fetch Artifacts based on Commit Passed by Trigger
-kubernetes-build-commit:
-  image: buildpack-deps:stretch
-  stage: cncf-artifacts
-  script:
-    - apt update && apt -y install jq
-    - echo "$KUBERNETES_COMMIT"
-    - >
-      if [ -z "${KUBERNETES_COMMIT}" ]; then
-        exit 0 #Should Show Skipped on Gitlab CI FIXME
-      else
-        echo "Checking for Container Artifact on Commit"
-
-        echo "Fetch Full SHA" 
-        SHA=$(curl --header "PRIVATE-TOKEN: ${TOKEN}" "https://gitlab.cncf.ci/api/v4/projects/14/repository/commits/${KUBERNETES_COMMIT}" | jq --raw-output '.id')
-        echo ${SHA}
-
-        echo "Fetch Most Recent Job ID's on Commit"
-        COMPILE_JOB=$(curl --header "PRIVATE-TOKEN: ${TOKEN}" "https://gitlab.cncf.ci/api/v4/projects/14/repository/commits/${SHA}/statuses" | jq '.[] | select(.name=="compile")' | jq -s 'sort_by(.created_at)' | jq '.[0] | .id')
-        echo ${COMPILE_JOB}
-        
-        CONTAINER_JOB=$(curl --header "PRIVATE-TOKEN: ${TOKEN}" "https://gitlab.cncf.ci/api/v4/projects/14/repository/commits/${SHA}/statuses" | jq '.[] | select(.name=="container")' | jq -s 'sort_by(.created_at)' | jq '.[0] | .id')
-
-        echo "Fetch Artifact"
-        curl -s -o data/kubernetes.env -L "$BASE_URL/kubernetes/kubernetes/-/jobs/${CONTAINER_JOB}/artifacts/raw/release.env"
-
-        echo "Verify Artifact"
-        if source ./data/kubernetes.env && env | grep KUBERNETES; then
-        cat data/kubernetes.env
-        else
-          echo "Trigger Jobs for missing Artifacts"
-          
-          PROJECT_COMPILE_JOB=$(curl -X POST --header "PRIVATE-TOKEN: ${TOKEN}" "https://gitlab.cncf.ci/api/v4/projects/14/jobs/${COMPILE_JOB}/retry" | jq '.id')
-          echo $PROJECT_COMPILE_JOB
-          echo 'Wait for Build "FIX ME / HACK"'
-          until [ "$COMPILE_JOB_STATUS" == '"success"' ]; do COMPILE_JOB_STATUS="$(curl -s --header "PRIVATE-TOKEN:${TOKEN}" "https://gitlab.cncf.ci/api/v4/projects/14/jobs/${PROJECT_COMPILE_JOB}" | jq -s '.[] | .status')" ; sleep 0.5 ; done ; echo 'Build Compleate'
-          
-          PROJECT_CONTAINER_JOB=$(curl -X POST --header "PRIVATE-TOKEN: ${TOKEN}" "https://gitlab.cncf.ci/api/v4/projects/14/jobs/${CONTAINER_JOB}/retry" | jq '.id')
-          until [ "$CONTAINER_JOB_STATUS" == '"success"' ]; do CONTAINER_JOB_STATUS="$(curl -s --header "PRIVATE-TOKEN:${TOKEN}" "https://gitlab.cncf.ci/api/v4/projects/14/jobs/${PROJECT_CONTAINER_JOB}" | jq -s '.[] | .status')" ; sleep 0.5 ; done ; echo 'Container Build Compleate'
-          
-          curl -s -o data/kubernetes.env -L "$BASE_URL/kubernetes/kubernetes/-/jobs/${PROJECT_CONTAINER_JOB}/artifacts/raw/release.env"
-          cat data/kubernetes.env
-        fi
-      fi
-  artifacts:
-    name: "${CI_JOB_NAME}_${CI_COMMIT_REF_NAME}"
-    untracked: true
-    expire_in: 5 weeks
-    paths:
-      - ./data
-
-
-cross-cloud-stable:
-  stage: cncf-artifacts
+Cross-Cloud:
+  stage: Build
   script:
     - docker login -u "gitlab-ci-token" -p "$CI_JOB_TOKEN" $CI_REGISTRY
     - docker build --pull -t "$CI_REGISTRY_IMAGE/provisioning:$CI_COMMIT_REF_SLUG" .
     - docker push "$CI_REGISTRY_IMAGE/provisioning:$CI_COMMIT_REF_SLUG"
 
-cross-cloud-socat:
-  stage: cncf-artifacts
+Socat:
+  stage: Build
   script:
     - docker login -u "gitlab-ci-token" -p "$CI_JOB_TOKEN" $CI_REGISTRY
     - docker build --pull -t "$CI_REGISTRY_IMAGE/socat:$CI_COMMIT_REF_SLUG" ./socat/
     - docker push "$CI_REGISTRY_IMAGE/socat:$CI_COMMIT_REF_SLUG"
 
+.build_source: &build_source
+  image: buildpack-deps:stretch
+  stage: Artifacts
+  allow_failure: true
+  variables:
+    # SOURCE
+    # ORG: MUST BE SET
+    # PROJECT: MUST BE SET
+    # PROJECT_ID: MUST BE SET
+  script:
+    - apt update && apt -y install jq
+    - >
+      if [ -z "${SOURCE}" ]; then
+        exit 1 #Should Show Skipped on Gitlab CI FIXME
+      elif [ "${DISABLE_SOURCE}" == "yes" ]; then
+        exit 1 #Should Show Skipped on Gitlab CI FIXME
+      else
+        PROJECT_JOB=$(curl --header "PRIVATE-TOKEN:${TOKEN}" "https://gitlab.cncf.ci/api/v4/projects/$PROJECT_ID/pipelines/${SOURCE}/jobs?scope=success" | jq '.[] | select(.name=="container") | .id') 
+        curl -s -o data/"$PROJECT".env -L "$BASE_URL/${ORG}/${PROJECT}/-/jobs/${PROJECT_JOB}/artifacts/raw/release.env"
+        cat data/"$PROJECT".env
+      fi
+
+  artifacts:
+    name: "${CI_JOB_NAME}_${CI_COMMIT_REF_NAME}"
+    untracked: true
+    expire_in: 5 weeks
+    paths:
+      - ./data
+
+.build_branch: &build_branch
+  image: buildpack-deps:stretch
+  stage: Artifacts
+  allow_failure: true
+  variables:
+    # BRANCH: MUST BE SET
+    # ORG: MUST BE SET
+    # PROJECT: MUST BE SET
+    # PROJECT_TOKEN: MUST BE SET
+    # PROJECT_ID: MUST BE SET
+  script:
+    - apt update && apt -y install jq
+    - >
+      if [ -z "${BRANCH}" ]; then
+        exit 1 #Should Show Skipped on Gitlab CI FIXME
+      else
+        echo "Checking for Latest Build"
+        curl -s -L -o data/${PROJECT}.url "${BASE_URL}/${ORG}/${PROJECT}/builds/artifacts/${BRANCH}/file/release.env?job=container"
+        if cat data/"$PROJECT".url | sed -n 's/.*href="\([^"]*\).*/\1/p' | grep artifacts/raw ; then
+        RELEASE_ENV=$(cat data/${PROJECT}.url | sed -n 's/.*href="\([^"]*\).*/\1/p' | grep artifacts/raw | tail -1)
+        curl -o data/${PROJECT}.env -L ${BASE_URL}/$RELEASE_ENV
+        cat data/${PROJECT}.env
+        else
+          # PROJECT_PIPELINE=$(curl -X POST -F token=$CI_JOB_TOKEN -F ref=$BRANCH https://gitlab.cncf.ci/api/v4/projects/$PROJECT_ID/trigger/pipeline | jq '.id')
+          PROJECT_PIPELINE=$(curl -X POST -F token=$PROJECT_TOKEN -F ref=$BRANCH -F "variables[BUILD_TRIGGER]=yes" https://gitlab.cncf.ci/api/v4/projects/$PROJECT_ID/trigger/pipeline | jq '.id')
+
+          echo 'Wait for Build "FIX ME / HACK"'
+          until [ "$JOB_STATUS" == '"success"' ]; do JOB_STATUS="$(curl -s --header "PRIVATE-TOKEN:${TOKEN}" "https://gitlab.cncf.ci/api/v4/projects/$PROJECT_ID/pipelines/${PROJECT_PIPELINE}/jobs?scope=success" | jq '.[] | select(.name=="container") | .status')" ; sleep 0.5 ; done ; echo 'Build Compleate'
+          PROJECT_JOB=$(curl --header "PRIVATE-TOKEN:${TOKEN}" "https://gitlab.cncf.ci/api/v4/projects/$PROJECT_ID/pipelines/${PROJECT_PIPELINE}/jobs?scope=success" | jq '.[] | select(.name=="container") | .id') 
+          curl -s -o data/"$PROJECT".env -L "$BASE_URL/${ORG}/${PROJECT}/-/jobs/${PROJECT_JOB}/artifacts/raw/release.env"
+          cat data/"$PROJECT".env
+        fi
+      fi
+  artifacts:
+    name: "${CI_JOB_NAME}_${CI_COMMIT_REF_NAME}"
+    untracked: true
+    expire_in: 5 weeks
+    paths:
+      - ./data
+
+.build_commit: &build_commit
+  image: buildpack-deps:stretch
+  stage: Artifacts
+  allow_failure: true
+  variables:
+    # COMMIT: MUST BE SET
+    # ORG: MUST BE SET
+    # PROJECT: MUST BE SET
+    # PROJECT_ID: MUST BE SET
+  script:
+    - apt update && apt -y install jq
+    - echo "$COMMIT"
+    - >
+      if [ -z "${COMMIT}" ]; then
+        exit 1 #Should Show Skipped on Gitlab CI FIXME
+      else
+        echo "Checking for Container Artifact on Commit"
+
+        echo "Fetch Full SHA" 
+        SHA=$(curl --header "PRIVATE-TOKEN: ${TOKEN}" "https://gitlab.cncf.ci/api/v4/projects/9/repository/commits/${COMMIT}" | jq --raw-output '.id')
+        echo ${SHA}
+
+        echo "Fetch Most Recent Job ID's on Commit"
+        COMPILE_JOB=$(curl --header "PRIVATE-TOKEN: ${TOKEN}" "https://gitlab.cncf.ci/api/v4/projects/${PROJECT_ID}/repository/commits/${SHA}/statuses" | jq '.[] | select(.name=="compile")' | jq -s 'sort_by(.created_at)' | jq '.[0] | .id')
+        echo ${COMPILE_JOB}
+        
+        CONTAINER_JOB=$(curl --header "PRIVATE-TOKEN: ${TOKEN}" "https://gitlab.cncf.ci/api/v4/projects/${PROJECT_ID}/repository/commits/${SHA}/statuses" | jq '.[] | select(.name=="container")' | jq -s 'sort_by(.created_at)' | jq '.[0] | .id')
+
+        echo "Fetch Artifact"
+        curl -s -o data/${PROJECT}.env -L "$BASE_URL/${ORG}/${PROJECT}/-/jobs/${CONTAINER_JOB}/artifacts/raw/release.env"
+
+        echo "Verify Artifact"
+        if source ./data/${PROJECT}.env && env | grep ${PROJECT}; then
+        cat data/${PROJECT}.env
+        else
+          echo "Trigger Jobs for missing Artifacts"
+          
+          PROJECT_COMPILE_JOB=$(curl -X POST --header "PRIVATE-TOKEN: ${TOKEN}" "https://gitlab.cncf.ci/api/v4/projects/${PROJECT_ID}/jobs/${COMPILE_JOB}/retry" | jq '.id')
+          echo $PROJECT_COMPILE_JOB
+          echo 'Wait for Build "FIX ME / HACK"'
+          until [ "$COMPILE_JOB_STATUS" == '"success"' ]; do COMPILE_JOB_STATUS="$(curl -s --header "PRIVATE-TOKEN:${TOKEN}" "https://gitlab.cncf.ci/api/v4/projects/${PROJECT_ID}/jobs/${PROJECT_COMPILE_JOB}" | jq -s '.[] | .status')" ; sleep 0.5 ; done ; echo 'Build Compleate'
+          
+          PROJECT_CONTAINER_JOB=$(curl -X POST --header "PRIVATE-TOKEN: ${TOKEN}" "https://gitlab.cncf.ci/api/v4/projects/${PROJECT_ID}/jobs/${CONTAINER_JOB}/retry" | jq '.id')
+          until [ "$CONTAINER_JOB_STATUS" == '"success"' ]; do CONTAINER_JOB_STATUS="$(curl -s --header "PRIVATE-TOKEN:${TOKEN}" "https://gitlab.cncf.ci/api/v4/projects/${PROJECT_ID}/jobs/${PROJECT_CONTAINER_JOB}" | jq -s '.[] | .status')" ; sleep 0.5 ; done ; echo 'Container Build Compleate'
+          
+          curl -s -o data/${PROJECT}.env -L "$BASE_URL/${ORG}/${PROJECT}/-/jobs/${PROJECT_CONTAINER_JOB}/artifacts/raw/release.env"
+          cat data/${PROJECT}.env
+        fi
+      fi
+
+  artifacts:
+    name: "${CI_JOB_NAME}_${CI_COMMIT_REF_NAME}"
+    untracked: true
+    expire_in: 5 weeks
+    paths:
+      - ./data
+
+
 # Deploy Template used for Each Cloud
 .kubernetes_deploy_template: &kubernetes_deploy_template
   allow_failure: true
   image: ${CI_REGISTRY}/cncf/cross-cloud/provisioning:$CI_COMMIT_REF_SLUG
-  stage: cross-cloud
+  stage: Cross-Cloud
   variables:
     CLOUD: MUST BE SET
   script:
@@ -155,7 +197,7 @@ cross-cloud-socat:
 .kubernetes_cloud_destroy_template: &kubernetes_cloud_destroy_template
   allow_failure: true
   image: ${CI_REGISTRY}/cncf/cross-cloud/provisioning:$CI_COMMIT_REF_SLUG
-  stage: cross-cloud
+  stage: Cross-Cloud
   when: manual
   variables:
     CLOUD: MUST BE SET
